services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-root
    ports:
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
